### ISSUE TITLE
Dúvida campo source do JSON

### ISSUE THREAD

**Issue by brunoFallis** [olxbr/lead_integration#5]
Boa tarde,

Finalizamos a integração de leads com a OLX, porém nos primeiros testes o campo source está chegando minusculo ("olx") e na documentação é informado que será passado OLX no campo abaixo, qual a maneira correta do campo source ?

**Comment by rafaelsbatista** [comment]
Boa tarde,

O certo é minúsculo. Obrigado pelo report, iremos atualizar a documentação!
